kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: registry.dockerpod1.zrail.net/bugsplat-rb
      registry: registry.dockerpod1.zrail.net
  - name: push_compose
    image: appleboy/drone-scp
    settings:
      host: dockerpod1.zrail.net
      username: root
      key:
        from_secret: ssh_key
      target: /tmp/bugsplat-rb-docker-compose.yaml
      source: docker-compose.yaml
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: dockerpod1.zrail.net
      username: root
      key:
        from_secret: ssh_key
      script:
        - docker-compose pull /tmp/bugsplat-rb-docker-compose.yaml
        - docker-compose up /tmp/bugsplat-rb-docker-compose.yaml
