kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: registry.dockerpod1.zrail.net/bugsplat-rb
      registry: registry.dockerpod1.zrail.net
  - name: deploy
    image: maniack/drone-portainer:0.8
    portainer: 
      address: https://portainer.zrail.net
      endpoint: dockerpod1
    stack:
      name: bugsplat-rb
      path: docker-compose.yaml
    secrets: [ portainer_username, portainer_password ]
