version: "3"

networks:
  traefik:
    external:
      name: traefik_default
      
services:
  bugsplat-server:
    image: registry.dockerpod1.zrail.net/bugsplat-rb:latest
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 3000
    networks:
      - traefik
    labels:
      - "traefik.frontend.rule=Host:bugsplat.dockerpod1.zrail.net"
      - "traefik.port=3000"
      - "traefik.docker.network=traefik_default"
 